version: '3.4'

services:
  postgres:
    image: postgres
  mongodb:
    image: mongo
  rabbitmq:
    image: rabbitmq:management-alpine
  auction-svc:
    image: akaWild/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
  search-svc:
    image: akaWild/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
volumes:
  pgdata:
  mongodata:
