version: '3.4'

services:
  postgres:
    image: postgres
  mongodb:
    image: mongo
  rabbitmq:
    image: rabbitmq:management-alpine
  auction-svc:
    image: akaWild/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
  search-svc:
    image: akaWild/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
  identity-svc:
    image: akaWild/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
  gateway-svc:
    image: akaWild/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
  bid-svc:
    image: akaWild/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
  notify-svc:
    image: akaWild/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
volumes:
  pgdata:
  mongodata:
