version: '3.4'

services:
  # auctionservice:
    # image: ${DOCKER_REGISTRY-}auctionservice
    # build:
    #   context: .
    #   dockerfile: src/AuctionService/Dockerfile
  postgres:
    image: postgres
  mongodb:
    image: mongo
  rabbitmq:
    image: rabbitmq:management-alpine
volumes:
  pgdata:
  mongodata:
