version: '3.4'

networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    environment:
      - POSTGRES_DB=auctions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      custom:
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
    networks:
      custom:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  auction-svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080;7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=auctions;User Id=postgres;Password=postgrespw
      - IdentityServiceUrl=http://identity-svc:8080
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:8080
    ports:
      - 7001:8080
      - 7777:7777
    depends_on: 
      - postgres
      - rabbitmq
    networks:
      custom:
  search-svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc:8080
    ports:
      - 7002:8080
    depends_on: 
      - mongodb
      - rabbitmq
      - auction-svc
    networks:
      custom:
  identity-svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=identity;User Id=postgres;Password=postgrespw
      - ClientApp=http://app.carsauction.com
      - VIRTUAL_HOST=id.carsauction.com
    ports:
      - 8080:8080
    depends_on: 
      - postgres
    networks:
      custom:
        ipv4_address: 10.5.0.100
  gateway-svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ClientApp=https://app.carsauction.com
      - VIRTUAL_HOST=api.carsauction.com
    networks:
      custom:
  bid-svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc:8080
      - GrpcAuction=http://auction-svc:7777
    ports:
      - 7003:8080
    depends_on: 
      - mongodb
      - rabbitmq
    networks:
      custom:
  notify-svc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:8080
    depends_on: 
      - rabbitmq
    networks:
      custom:
  web-app:
    environment:
      - NEXTAUTH_SECRET=somethingreallyreallysecret
      - NEXTAUTH_URL=http://app.carsauction.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc:8080/
      - ID_URL=http://id.carsauction.com:8080
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc:8080/notifications
      - VIRTUAL_HOST=app.carsauction.com
      - VIRTUAL_PORT=3000
    extra_hosts:
      - id.carsauction.com:10.5.0.100
    volumes:
      - /var/lib/web/data
    networks:
      custom:
  nginx-proxy:
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
        ipv4_address: 10.5.0.110
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
    

